### ISSUE TITLE
hello，this is my problem

### ISSUE THREAD

**Issue by buying01** [webjames/heroku-wordpress-svbtle#1]
Installing Plugin: FileBrowser 0.5.5
Downloading install package from http://downloads.wordpress.org/plugin/filebrowser.0.5.5.zip…

Unpacking the package…

Abort class-pclzip.php : Missing zlib extensions

what should i do？
thanks！

**Comment by webjames** [comment]
Hello @buying01 
This is not an issue per say, this is a limitation of Heroku, and using Wordpress on it. 

Heroku does not have block storage, as such you need to publish themes/plugins locally then push them to Heroku. You can then activate them normally within the Wordpress admin interface. this will vary by plugin in some cases, but in most cases plugins sit in the /wp-content/plugins directory.

**Comment by buying01** [comment]
thanks,i see!

2013/3/27 webjames notifications@github.com
